### ISSUE TITLE
Tidying up the main report .ipynb

### ISSUE THREAD

**Issue by killerninja8** [UBC-MDS/dsci_522_group_8_bank_marketing_project#10]
Hey Team, 

Great work on the report!  

I feel like we can tidy up our analysis by re-adjusting titles, using markdown cells better and more. 

If so, let's discuss this at our next meeting and move forward with some changes.

**Comment by Rachel0619** [comment]
yeah I think Readjusting the titles are necessary since we should have standard structure.
