### ISSUE TITLE
Please review README.md, CONTRIBUTING.md, and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by killerninja8** [UBC-MDS/dsci_522_group_8_bank_marketing_project#11]
Hello Team, 

Just uploaded the README.md, CONTRIBUTING.md, and CODE_OF_CONDUCT.md

We need to fill the key takeaway and dependencies section, amongst some others. 

I have left repeated `X` marks in spots we need to fill out. 

Any and all feedback + changes would be appreciated :)

**Comment by Rachel0619** [comment]
Yeah I think for dependencies, these following three would be sufficient:
conda (version 23.9.0 or higher)
nb_conda_kernels (version 2.3.1 or higher)
Python and packages listed in [environment.yml]

I can discuss this later in the meeting

**Comment by killerninja8** [comment]
Thanks for clarifying, Rachel!
