### ISSUE TITLE
Week 2 Minutes of Meeting (MoM)

### ISSUE THREAD

**Issue by killerninja8** [UBC-MDS/dsci_522_group_8_bank_marketing_project#23]
**Docker Tasks:** 
              @rafecchang,  

**Create 4 or more functions, at least one each, with tests. Some functions we discussed in our 21/11/23 meeting:**
             1. Exploratory Data Analysis Plotting abstraction/function @killerninja8 
             2. Preprocessing function 
             3. Cross-validation / Model Selection / Other ML functions
             4. Result reporting function 
             5. ...

**Render to HTML**

@killerninja8 @Rachel0619 @rafecchang @AnuBanga - feel free to confirm what you are working on. Thanks :)

**Comment by AnuBanga** [comment]
> **Docker Tasks:** @rafecchang,
> 
> **Create 4 or more functions, at least one each, with tests. Some functions we discussed in our 21/11/23 meeting:** 1. Exploratory Data Analysis Plotting abstraction/function @killerninja8 2. Preprocessing function  @AnuBanga 3. Cross-validation / Model Selection / Other ML functions 4. Result reporting function 5. ...
> 
> **Render to HTML**
> 
> @killerninja8 @Rachel0619 @rafecchang @AnuBanga - feel free to confirm what you are working on. Thanks :)

**Comment by Rachel0619** [comment]
yeah I think for now, we are making progress on building container and Rafe is taking care of that part. 
For the function part, I think it would be better for us to discuss which parts are we going to modulize and then split the tasks.

**Comment by AnuBanga** [comment]
I will work on this part.
3. Cross-validation / Model Selection / Other ML functions

**Comment by Rachel0619** [comment]
Well done folks

**Comment by Rachel0619** [comment]
Well done folks
