### ISSUE TITLE
Abstract code from literate code document to functions a modular filename

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/dsci_522_group_8_bank_marketing_project#25]
Guys, Let's discuss during the meeting today which parts in out literate code documents should be modularized to functions cuz for now it's not quite clear.

**Comment by Rachel0619** [comment]
for now, I think we have the few options:
1. EDA plotting
2. Preprocessing
3. Model tuning
4. Reading data and save file

Feel free to choose from these modules and write functions based on them

**Comment by killerninja8** [comment]
I'll work on the EDA plotting functions and tests. Should be done very soon!

**Comment by Rachel0619** [comment]
The functions are working well now with good documentation and code style.
