### ISSUE TITLE
What kind of tests should we implement for each function

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/dsci_522_group_8_bank_marketing_project#26]
Another topic we need to discuss here is which kind of tests should we carry out on our functions. I can name a few now:
1: check the datatype
2. check the function is getting the correct parameter

Feel free to come with more!

**Comment by AnuBanga** [comment]
Adding in above list:-
3. check for return values if values are non-negative

**Comment by Rachel0619** [comment]
Great. For the preprocessor part, I will write the following three test:
1. test whether the function is returning dataframes.
2. test whether the function will raise error when we call the function with parameters that have invalid data types.
3. test whether the shape of my result dataframes are as expected.
 I will use some helper data to make our life easier.

**Comment by killerninja8** [comment]
Great ideas, team! For the EDA plots part, I'll write tests to check if: 
data type is correct, none is not returned, the result is a histogram or barplot, x and y encodings are correct, alt.Repeat chart is used, one of the correct marks is used, and more.

**Comment by Rachel0619** [comment]
well done folks
