### ISSUE TITLE
Milestone2 Status

### ISSUE THREAD

**Issue by AnuBanga** [UBC-MDS/dsci_522_group_8_bank_marketing_project#29]
Maintaining a to-do list allows us to monitor tasks and indicate their completion as we go along.
1. test function for scoring_metrics -  done and tested

Please complete the list with completed and pending tasks.

**Comment by killerninja8** [comment]
Thanks for sharing this issue, Anu. 

I've prepared 3 functions for EDA and am writing unit tests now. 

I may be able to write some more functions and tests later today. 

PS: I've also made a to-do list in the projects tab (with a to-do view) if needed.

**Comment by Rachel0619** [comment]
I think we are making great progress so far for milestone 2. Just need to release the repo
