### ISSUE TITLE
Should we delete all the branches that we are no longer using to tidy up our project github?

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/dsci_522_group_8_bank_marketing_project#32]
Please review the branches that are no longer in need

**Comment by killerninja8** [comment]
I'm not really sure so I'll go with what everyone says. I think there's no harm in keeping them though.

**Comment by AnuBanga** [comment]
We can keep them for this milestone. Then we will decide in next milestone.

**Comment by Rachel0619** [comment]
Good idea

**Comment by killerninja8** [comment]
Great work!
