### ISSUE TITLE
Docker Publish has failed

### ISSUE THREAD

**Issue by killerninja8** [UBC-MDS/dsci_522_group_8_bank_marketing_project#34]
Hey team, 

Docker-publish has failed. 

Error: Username and password required

How do we resolve it? 

@rafecchang maybe you have to add your username and password to github secrets?

**Comment by Rachel0619** [comment]
Yeah I think so. Action required here

**Comment by Rachel0619** [comment]
I've granted Rafe the role of admin. Should work now

**Comment by rafecchang** [comment]
Just ran the workflow file and I think it's live! I cut down the packages to ones that are in use; please let me know if it works!

**Comment by Rachel0619** [comment]
Problem solved
