### ISSUE TITLE
Change log to keep track all the changes we made for the project

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/dsci_522_group_8_bank_marketing_project#53]
Please add any meaningful changes/adjustment you made here to keep track of the project.

**Comment by Rachel0619** [comment]
Added jupyter book to docker file. Docker image need to be rebuilt

**Comment by Rachel0619** [comment]
2. Moved preprocessor.py from src to scripts

**Comment by AnuBanga** [comment]
1. Created model_selection.py and scoring_metric.py
2. Able to create csv files in results folder and displaying those results in jupyter notebook

**Comment by Rachel0619** [comment]
done
