### ISSUE TITLE
Enter the terminal commands needed to run the analysis here

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/dsci_522_group_8_bank_marketing_project#60]

**Comment by Rachel0619** [comment]
python download_data.py \
   --url="https://archive.ics.uci.edu/static/public/222/bank+marketing.zip" \
   --write_to="data/raw"

python scripts/unzip.py \
   --path_to_zip_file="data/raw/bank.zip" \
   --directory_to_extract_to="data/raw"

**Comment by killerninja8** [comment]
# Perform exploratory data analysis (EDA) on the given df
python scripts/EDA.py \
   --data-frame="data/raw/bank/bank-full.csv" \
   --plot-to="results/figures"

**Comment by Rachel0619** [comment]
# split train_df and test_df into features and target and create preprocessor
```
python src/preprocessor.py \
   --raw_train=data/split/train_df.csv \
   --raw_test=data/split/test_df.csv \
   --data_to=data/processed \
   --preprocessor_to=results/models
```

**Comment by AnuBanga** [comment]
# Different model fitting and scoring, create model pipeline pickle 

```
python scripts/model_selection.py \
     --x_train=data/processed/X_train.csv \
     --y_train=data/processed/y_train.csv  \
     --preprocessor=results/models/preprocessor.pickle \
      --pipeline-to=results/models \
      --results_to=data/model_scoring \
      --seed=522
```

**Comment by rafecchang** [comment]
# Altered: Optimization and Accuracy/Recall Scores
 
 python scripts/optimization.py \
 --df=data/bank-full.csv \
 --x_test=data/processed/X_test.csv \
 --y_test=data/processed/y_test.csv \
 --model_type=results/models/model_pipeline.pickle \
 --results_to=results/metrics \
 --results_to_1=results/metrics

**Comment by Rachel0619** [comment]
done and no need anymore
