### ISSUE TITLE
Things need to be improved based on feedbacks from milestone 1

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/dsci_522_group_8_bank_marketing_project#62]
Guys, I have documented the things we need to fix and improve for the project so far according to the grader's feedback:
1. include a Creative Commons [Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)](https://creativecommons.org/licenses/by-nc-nd/4.0/) license for the project report.
2. Redo the methods part.
3. Redo the discussion part:
Findings from project are not linked back to the application domain.
Assumptions and limitations of methods and findings are not discussed.
4. Double check the reproducibility before we submit
5. Double check the release file before we submit

**Comment by killerninja8** [comment]
Thank your for summarising these, Rachel!

**Comment by Rachel0619** [comment]
6. Update the usage part in README.md file to insure reproducibility

**Comment by AnuBanga** [comment]
Thanks for summarizing points

**Comment by Rachel0619** [comment]
done
