### ISSUE TITLE
Modify JupyterBook

### ISSUE THREAD

**Issue by killerninja8** [UBC-MDS/dsci_522_group_8_bank_marketing_project#68]
Hi Team, Our JupyterBook is finally live. We need to modify the jb and provide instructions to run it. Do we have to host it on gh-pages as well?

**Comment by Rachel0619** [comment]
TBH jupyter book is new to me. Let's discuss this later

**Comment by killerninja8** [comment]
Sure thing, we can go over it later!

**Comment by AnuBanga** [comment]
We need to push rendered html on github repo. This is pending

**Comment by Rachel0619** [comment]
problem solved
