### ISSUE TITLE
Any ideas about how to put plots, figures and tables into jupyter notebook?

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/dsci_522_group_8_bank_marketing_project#77]
Let's discuss this in tmr's meeting cuz I'm lost here

**Comment by killerninja8** [comment]
Sure!

**Comment by killerninja8** [comment]
I think you can use {{ df }} in a markdown cell, replace df with the name of the dataframe you wish to display

**Comment by Rachel0619** [comment]
problem solved.
